### ISSUE TITLE
ToDO for finish

### ISSUE THREAD

**Issue by znichola** [znichola/miniRT#27]
- [x] - Cylinder
- [x] - - it is broken, must fix
- [x] - - - poi on cap
- [x] - - - normal on cap
- [x] - - - normal on body, all cases, don't cheat with the weird inside out cylinder
- [x] - - Refactor sphere to use new poi variable
- [x] - - FIx plane rendering
- [x] - Object selection UI indicator
- [x] - Object property modifier
- [x] - Finalise the frikin' parsing
- [x] - Refactor pix shader to use `t_intersection`
- [x] - Plug leaks! 
- [ ] - - Do more thorough tests

Bonus !

- [x] - checkerboard
- [x] - - cylinder uv unwrap!
- [x] - texture integration
- [x] - - cylinder uv unwrap!
- [ ] - skybox
- [x] - multithreading !?
- [x] - cone! 
- [x] - - same todo list as cylinder

For now...
